version: "3.7"

services:
  media1:
    image: plexinc/pms-docker
    container_name: media1
    restart: unless-stopped
    ports: 
      - 32401:32400/tcp
      # - 3005:3005/tcp
      # - 8324:8324/tcp
      # - 32469:32469/tcp
      # - 1900:1900/udp
      # - 32410:32410/udp
      # - 32412:32412/udp
      # - 32413:32413/udp
      # - 32414:32414/udp
    environment:
      - TZ=Europe/Belgrade
      - PLEX_CLAIM=(insert claim token here)
    volumes:
      - /opt/movtex/media1/config:/config
      - /opt/movtex/media1/transcodes/to:/transcode
      - /opt/movtex/data/:/data
    networks: 
        - plex_network
    
    
  media2:
    image: plexinc/pms-docker
    container_name: media2
    restart: unless-stopped
    ports: 
        - 32402:32400/tcp
        # - 3005:3005/tcp
        # - 8324:8324/tcp
        # - 32469:32469/tcp
        # - 1900:1900/udp
        # - 32410:32410/udp
        # - 32412:32412/udp
        # - 32413:32413/udp
        # - 32414:32414/udp
    environment:
        - TZ=Europe/Belgrade
        - PLEX_CLAIM=(insert claim token here)
    volumes:
        - /opt/movtex/media2:/config
        - /opt/movtex/media2/transcodes/to:/transcode
        - /opt/movtex/data/:/data
    networks: 
        - plex_network

  media3:
    image: plexinc/pms-docker
    container_name: media3
    restart: unless-stopped
    ports: 
        - 32403:32400/tcp
        # - 3005:3005/tcp
        # - 8324:8324/tcp
        # - 32469:32469/tcp
        # - 1900:1900/udp
        # - 32410:32410/udp
        # - 32412:32412/udp
        # - 32413:32413/udp
        # - 32414:32414/udp
    environment:
        - TZ=Europe/Belgrade
        - PLEX_CLAIM=(insert claim token here)
    volumes:
        - /opt/movtex/media3:/config
        - /opt/movtex/media3/transcodes/to:/transcode
        - /opt/movtex/data/:/data
    networks: 
        - plex_network


  media4:
    image: plexinc/pms-docker
    container_name: media4
    restart: unless-stopped
    ports: 
        - 32404:32400/tcp
        # - 3005:3005/tcp
        # - 8324:8324/tcp
        # - 32469:32469/tcp
        # - 1900:1900/udp
        # - 32410:32410/udp
        # - 32412:32412/udp
        # - 32413:32413/udp
        # - 32414:32414/udp
    environment:
        - TZ=Europe/Belgrade
        - PLEX_CLAIM=(insert claim token here)
    volumes:
        - /opt/movtex/media4:/config
        - /opt/movtex/media4/transcodes/to:/transcode
        - /opt/movtex/data/:/data
    networks: 
        - plex_network
    
networks:
    plex_network:
        driver: bridge