version: '3'
services:
  tautulli1:
    image: tautulli/tautulli
    container_name: tautulli1
    restart: unless-stopped
    volumes:
      - /opt/media_stream/media1/tautulli/:/config
    environment:
      - PUID=<uid>
      - PGID=<gid>
      - TZ=<timezone>
    ports:
      - 8181:8181

  tautulli2:
    image: tautulli/tautulli
    container_name: tautulli2
    restart: unless-stopped
    volumes:
      - /opt/media_stream/media2/tautulli/:/config
    environment:
      - PUID=<uid>
      - PGID=<gid>
      - TZ=<timezone>
    ports:
      - 8182:8181
  
  tautulli3:
    image: tautulli/tautulli
    container_name: tautulli3
    restart: unless-stopped
    volumes:
      - /opt/media_stream/media3/tautulli/:/config
    environment:
      - PUID=<uid>
      - PGID=<gid>
      - TZ=<timezone>
    ports:
      - 8183:8181

  tautulli2:
    image: tautulli/tautulli
    container_name: tautulli4
    restart: unless-stopped
    volumes:
      - /opt/media_stream/media4/tautulli/:/config
    environment:
      - PUID=<uid>
      - PGID=<gid>
      - TZ=<timezone>
    ports:
      - 8184:8181